### ISSUE TITLE
消息会重复一遍怎么解决

### ISSUE THREAD

**Issue by Xiao-yux** [nonepkg/nonebot-plugin-puppet#7]

**Comment by j1g5awi** [comment]
不知道你所描述的是什么现象，请补充

**Comment by Xiao-yux** [comment]
就是链接到群后，不管什么信息都会重复发一遍

**Comment by Xiao-yux** [comment]
![Screenshot_2022-07-30-12-16-34-251_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/79674967/181872033-9c2136bf-c10f-4463-a2cf-af16973ff7d1.jpg)![Screenshot_2022-07-30-12-16-43-136_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/79674967/181872036-fb19b2aa-97cd-4fab-81be-dfb833f87ff7.jpg)

**Comment by j1g5awi** [comment]
请查看机器人根目录下的 data/puppet/conv_mapping.yml，检查其转发群号是否有重复。

如果没有，检查下机器人在出现上述情况时的日志，是否触发了两次 nonebot_plugin_puppet 的 Matcher。

如果没有，再检查下自己有没有无意中打开了两个 NoneBot 实例。
